# blog
sdzblog_index:
    pattern:  /{index}
    defaults: { _controller: SdzBlogBundle:Blog:index, index: 1 }
    requirements:
        index:  \d+

# post
sdzblog_post_view:
    pattern:  /post/{post_id}
    defaults: { _controller: SdzBlogBundle:Post:view }
    requirements:
        post_id:  \d+

sdzblog_post_add:
    pattern:  /post/new
    defaults: { _controller: SdzBlogBundle:Post:edit }

sdzblog_post_edit:
    pattern:  /post/{post_id}/edit
    defaults: { _controller: SdzBlogBundle:Post:edit }
    requirements:
        post_id:  \d+

sdzblog_post_delete:
    pattern:  /post/{post_id}/delete
    defaults: { _controller: SdzBlogBundle:Post:delete }
    requirements:
        post_id:  \d+

# comment
#sdzblog_comment_index: # this should be on post_view
sdzblog_comment_view:
    pattern:  /post/{post_id}#{comment_id}
    defaults: { _controller: SdzBlogBundle:Comment:view }
    requirements:
        post_id:  \d+
        comment_id:  \d+

sdzblog_comment_add:
    pattern:  /post/{post_id}#new
    defaults: { _controller: SdzBlogBundle:Comment:edit }
    requirements:
        post_id:  \d+

sdzblog_comment_edit:
    pattern:  /post/{post_id}#{comment_id}/edit
    defaults: { _controller: SdzBlogBundle:Comment:edit }
    requirements:
        post_id:  \d+
        comment_id:  \d+

sdzblog_comment_delete:
    pattern:  /post/{post_id}#{comment_id}/delete
    defaults: { _controller: SdzBlogBundle:Comment:view }
    requirements:
        post_id:  \d+
        comment_id:  \d+

# category
sdzblog_category_index:
    pattern: /categories
    defaults: { _controller: SdzBlogBundle:Category:index }

sdzblog_category_add:
    pattern: /category/new
    defaults: { _controller: SdzBlogBundle:Category:edit }

sdzblog_category_edit:
    pattern: /category/{category_id}/edit
    defaults: { _controller: SdzBlogBundle:Category:edit }
    requirements:
        category_id:  \d+

sdzblog_category_delete:
    pattern: /category/{category_id}/delete
    defaults: { _controller: SdzBlogBundle:Category:delete }
    requirements:
        category_id:  \d+